# Use the official Golang image to build the app
FROM golang:1.24 AS builder

WORKDIR /app

# Copy go.mod and go.sum
COPY go.mod go.sum ./
RUN go mod download

# Copy the rest of your code
COPY . .

# Build the binary
RUN go build -o main ./cmd/main.go

# Use a minimal base image to run the binary
FROM debian:stable-slim

WORKDIR /root/

# Copy the binary from the previous stage
COPY --from=builder /app/main ./

# Grant execute permissions to the binary
RUN chmod +x main

# Expose the application port
EXPOSE 8080

# Command to run the executable
CMD ["./main"]
